version: '3.8'

services:
  ssrf:
    build: .
    ports:
      - "5002:5002"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG:-L3m0nCTF{G4NG5T3R_G4N35H_SQLi_Byp4ss_4nd_D3c1m4l_IP_SSrf_}}
